version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: debug.log
        maxBytes: 50000000 # 50MB
        backupCount: 2
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: error.log
        maxBytes: 50000000 # 50MB
        backupCount: 2
        encoding: utf8

#    slack_log_handler:
#        class: loggers.slack_logger.SlackLogHandler
#        level: ERROR
#        webhook_url: https://mattermost.domain.com/hooks/xxxxxxxx
#        fallback_webhook_url: https://hooks.slack.com/services/x/x/x

root:
    level: INFO
    handlers: [ debug_file_handler, console ]

loggers:
    "default":
        level: DEBUG
# Non root handlers are ADDED to root handlers. All extra loggers get whatever is in the root by default.
# This is where all the duplicates were coming from.
