version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    debug_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: dashboard.log
        maxBytes: 5000000 # 5MB
        backupCount: 1
        encoding: utf8


root:
    level: ERROR
    handlers: [debug_file_handler, console]

loggers:
  "default":
    level: DEBUG
#    handlers: [debug_file_handler]
# Non root handlers are ADDED to root handlers. All extra loggers get whatever is in the root by default.
# This is where all the duplicates were coming from.
